// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "3307405e155466fcf08a70e81eb6a97c"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"10b16020bc50555e41693a472b997c7a": "1f8b08000000000000ff748e314fc330108567dfaf383c25a84a76a42ca5d00d365674712eae85e3b31c3b5285fadf9183846060f0e2f7bef75d24f34196719189fd0ae096282963034a7bb11a4069ebf2a58c9d91a5b7329679262f3d87edaaff0ba3440d2d40dfe3e9886e45422321b0c94e0266c1ab948413651a69e5fa31329695a74ae44b92622f52f2778d62f4ce50453bd828d5c9fb28b17bfc9904984b30e882cb4d8b9fa06a8dd3fe2481e2b0e1c380f5e6eeccb9d1e7d7f7a797377d403df1c65ee2c221eb16d4e978d8c1017f191a0e5b0bcacd7b74376070be5a9417db3d5326df704a2da81ba88a9d782c16771f0ec35f07dce02b0000ffff4f2ef40a73010000",
		"575f64a47f36a5e7cac81390e9a784dd": "1f8b08000000000000ff74903b6bc33010c767dda7b86a28523032743464cdd60e6da06351dcb323ea17d2a90f8abf7b39393453c6d3fdfe0fdde2db0fdf138ef33b0d09208ccb1c190d28cd94384cbd0650ba0f7cce27d7ce63ddcfa7dc757e986bd1c6faf341df02520e4c1a2c00ff2c848f92f1226f9838e696f117d4ae40aeec6005e8f2d4e29112bf5d71c3b8bbb471472baa52b7428a119b3d6e164ff45524af81cf87f0cd395232a5a3ac8cf6cbd26cdf6cc4ace92e8caeb473f5ff642da8d015ebbb3d4e61903cc5eee0d90f8662b4a05600e59344df5f5b0a56a666bb66259cdaba3de7c970853e5958e12f0000ffff732ead8074010000",
		"f5af6f4a5eca022d18f1cde668c13ed9": "1f8b08000000000000ff3ccc414ec3400c85e1f5f8144fb3caa0aa39018b42d76c380072669c745432896c072155bd3ba2116cbcf1f7bf95f39527c1a4757423aaf3baa8a3a310a7ea976d38e665ee67d6ebc02ed63fdc7e2325a22f567ce079ef8f6f3c8bad9ca58b6588078c5bcb5dc28d28ece02c96bb6822251e10df458a8151d879609398fedca9947ff618c978da3faf4b73f9f604515d14370aa1ef712a05e717fc16b54d30dfc6111751a110547cd386563f29dc13d13dd14f000000ffffd99efe2af6000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("github.com/gobuffalo/buffalo-pop/v2/genny/newapp/templates", "../newapp/templates")
		b.SetResolver("grifts/db.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "f5af6f4a5eca022d18f1cde668c13ed9"})
		b.SetResolver("models/models.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "10b16020bc50555e41693a472b997c7a"})
		b.SetResolver("models/models_test.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "575f64a47f36a5e7cac81390e9a784dd"})
		}()

	return nil
}()
