// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "aa5079864222621c47b8b1835eadab86"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"0d4dd261a59e085078e02aa68e58a0d9": "1f8b08000000000000ff748eb14eec3010456bcf57cc73953cad928a0629cdb2b01d74b468924cbc168ec7726c4b2bb4ff8e1c240405851bdf7bee9940d33b19c65566761b805d83c4840d28edc46800a58d4d973c7693acbd91312f0b39e9d997abfe2b0c12fa72a7a105e87b3c1dd16e483889f73c252b1e93e05572c499128db471fd1819f3c67325d2254a3617c9e9ab4621383b51453b2814ebe4ff20a17bf89e0458b29fd07a9b9a163f40d51ac7fd4904c5bee0fd80f5eceecca9d1e797b7c7e7577d403d73612761659f740bea743cece0803f0c0dfbd282b2cb1efd1bd05b572dca89e99e28916b38c616d40d54c54e3c6683bb0f87e1b7036ef0190000ffff138fc2b776010000",
		"25797902602e6629df39f49ac17f37d6": "1f8b08000000000000ff74903b6bc33010c767dda7b86a28523032743464cdd60e6da06351dcb323ea17d2a90f8abf7b39393453c6d3fdfe0fdde2db0fdf138ef33b0d09208ccb1c190d28cd94384cbd0650ba0f7cce27d7ce63ddcfa7dc757e986bd1c6faf341df02520e4c1a2c00ff2c848f92f1226f9838e696f117d4ae40aeec6005e8f2d4e29112bf5d71c3b8bbb471472baa52b7428a119b3d6e164ff45524af81cf87f0cd395232a5a3ac8cf6cbd26cdf6cc4ace92e8caeb473f5ff642da8d015ebbb3d4e61903cc5eee0d90f8662b4a05600e59344df5f5b0a56a666bb66259cdaba3de7c970853e5958e12f0000ffff732ead8074010000",
		"9972e34a517633d024117a3a4b66c4e5": "1f8b08000000000000ff3ccc414ec3400c85e1f5f8144fb3caa0aa39018b42d76c380072669c745432896c072155bd3ba2116cbcf1f7bf95f39527c1a4757423aaf3baa8a3a310a7ea976d38e665ee67d6ebc02ed63fdc7e2325a22f567ce079ef8f6f3c8bad9ca58b6588078c5bcb5dc28d28ece02c96bb6822251e10df458a8151d879609398fedca9947ff618c978da3faf4b73f9f604515d14370aa1ef712a05e717fc16b54d30dfc6111751a110547cd386563f29dc13d13dd14f000000ffffd99efe2af6000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("github.com/gobuffalo/buffalo-pop/v2/genny/newapp/templates", "../newapp/templates")
		b.SetResolver("grifts/db.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "9972e34a517633d024117a3a4b66c4e5"})
		b.SetResolver("models/models.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "0d4dd261a59e085078e02aa68e58a0d9"})
		b.SetResolver("models/models_test.go.plush", packr.Pointer{ForwardBox: gk, ForwardPath: "25797902602e6629df39f49ac17f37d6"})
		}()

	return nil
}()
